#!/usr/bin/php
<?php

use cwc24\mqtt\Demo2\Scheduler\Daemon as SchedulerDaemon;

chdir( __DIR__ );
(@include_once '../../vendor/autoload.php') or die('Please install using composer, first!');

$nrWorkers  = 2;

try{
	$app	= new SchedulerDaemon( $nrWorkers );
	$app->run();
}
catch( Exception $e ){
	print( 'Exception: '.$e->getMessage().'.'.PHP_EOL );
	print( 'Trace: '.PHP_EOL.$e->getTraceAsString().'.'.PHP_EOL.PHP_EOL );
}
